name: Test and Deploy Laravel To Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME}}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
    - name: install npm Dependencies and build production
      run: heroku npm install && npm run prod
    - name: Seed Database
      run: heroku run php artisan migrate:refresh --force --seed
    - name: Run Symbolic Link
      run: heroku run /app/php/bin/php /app/www/artisan storage:link
